#!/bin/bash

export GOPATH=${PWD}/build

WORKSPACE_PATH="$GOPATH"
REL_PROJECT_PATH="github.com/dsoprea/go-xmlvisitor"
PROJECT_PATH="$WORKSPACE_PATH/src/$REL_PROJECT_PATH"

mkdir -p $PROJECT_PATH

rm -fr $PROJECT_PATH/xmlvisitor
rm -fr $PROJECT_PATH/commands/xmlvisitortest

cp -r xmlvisitor $PROJECT_PATH
cp -r commands $PROJECT_PATH

go get $REL_PROJECT_PATH/commands/xmlvisitortest
if [ $? -ne 0 ]; then
    echo "Get failed."
    exit 1
fi

BIN_OUTPUT_PATH=$WORKSPACE_PATH/bin
mkdir -p $BIN_OUTPUT_PATH

go build -o $BIN_OUTPUT_PATH/xmlvisitortest $REL_PROJECT_PATH/commands/xmlvisitortest
