export GOPATH=${PWD}

XMLVISITORTEST_EXECUTABLE_FILENAME=xmlvisitortest

XMLVISITOR_FQ_PACKAGE=xmlvisitor/xmlvisitor
XMLVISITOR_SOURCEFILES=src/${XMLVISITOR_FQ_PACKAGE}/*.go
XMLVISITORTEST_SOURCEFILES=${XMLVISITOR_SOURCEFILES} src/XMLVISITOR/${XMLVISITORTEST_EXECUTABLE_FILENAME}/*.go

.PHONY: all clean

all: bin/${XMLVISITORTEST_EXECUTABLE_FILENAME}

clean:
	rm -fr bin pkg 

bin/${XMLVISITORTEST_EXECUTABLE_FILENAME}: ${XMLVISITORTEST_SOURCEFILES}
	go get xmlvisitor/${XMLVISITORTEST_EXECUTABLE_FILENAME}
	go install xmlvisitor/${XMLVISITORTEST_EXECUTABLE_FILENAME}
